import { t } from "..";

describe("t", () => {
  it("looks up a nested key", () => {
    expect(t("common.retry")).toBe("Try again");
  });

  it("fills placeholders", () => {
    expect(t("planned.eyebrow", { id: "C11", phase: 3 })).toBe("C11 · Phase 3");
  });

  it("leaves a placeholder alone when no value is given", () => {
    expect(t("planned.eyebrow", { id: "C11" })).toBe("C11 · Phase {phase}");
  });

  it("keeps the two disclaimers word for word", () => {
    expect(t("disclaimer.shades")).toMatch(/^Shade colours are taken from the paint companies' own shade cards/);
    expect(t("disclaimer.ai")).toMatch(/^Previews are generated by AI\./);
  });
});
