import { getLanguage, plural, setLanguage, subscribeLanguage, t, tEn } from "..";
import { en } from "../en";
import { hi } from "../hi";

describe("t", () => {
  it("looks up a nested key", () => {
    expect(t("common.retry")).toBe("Try again");
  });

  it("fills placeholders", () => {
    expect(t("planned.eyebrow", { id: "C11", phase: 3 })).toBe("C11 · Phase 3");
  });

  it("leaves a placeholder alone when no value is given", () => {
    expect(t("planned.eyebrow", { id: "C11" })).toBe("C11 · Phase {phase}");
  });

  it("keeps the two disclaimers word for word", () => {
    expect(t("disclaimer.shades")).toMatch(/^Shade colours are taken from the paint companies' own shade cards/);
    expect(t("disclaimer.ai")).toMatch(/^Previews are generated by AI\./);
  });
});

describe("Hindi", () => {
  afterEach(() => setLanguage("en"));

  it("reads every string in the chosen language, and English again after", () => {
    setLanguage("hi");
    expect(t("common.retry")).toBe("फिर से कोशिश करें");
    expect(t("settings.title")).toBe("सेटिंग्स");
    setLanguage("en");
    expect(t("common.retry")).toBe("Try again");
  });

  it("fills placeholders in Hindi too", () => {
    setLanguage("hi");
    expect(t("settings.languagePhoneValue", { language: "English" })).toBe("फ़ोन की भाषा (English)");
  });

  // What the board's PDF prints: its font has Latin letters only.
  it("keeps print in English whatever the language", () => {
    setLanguage("hi");
    expect(tEn("board.pdfTitle")).toBe(en.board.pdfTitle);
    expect(t("pdf.page", { n: 1, total: 2 })).toBe("Page 1 of 2");
  });

  it("counts nought as one in Hindi, as English doesn't", () => {
    expect(plural(0, "questions.answeredOne", "questions.answeredN")).toBe(t("questions.answeredN", { n: 0 }));
    setLanguage("hi");
    expect(plural(0, "questions.answeredOne", "questions.answeredN")).toBe(t("questions.answeredOne", { n: 0 }));
    expect(plural(2, "questions.answeredOne", "questions.answeredN")).toBe(t("questions.answeredN", { n: 2 }));
  });

  it("tells listeners once per change", () => {
    const heard = jest.fn();
    const stop = subscribeLanguage(heard);
    setLanguage("hi");
    setLanguage("hi");
    stop();
    setLanguage("en");
    expect(heard).toHaveBeenCalledTimes(1);
    expect(getLanguage()).toBe("en");
  });

  // The type already demands every key; this guards what a type can't see.
  it("has every English string, with the same placeholders, and none left blank", () => {
    const holes = (s: string) => [...s.matchAll(/\{(\w+)\}/g)].map((m) => m[1]).sort().join(",");
    const problems: string[] = [];
    const walk = (e: Record<string, unknown>, h: Record<string, unknown> | undefined, at: string) => {
      for (const [k, v] of Object.entries(e)) {
        if (!at && (k === "pdf" || k === "dev")) continue;
        const key = at ? `${at}.${k}` : k;
        const theirs = h?.[k];
        if (typeof v === "string") {
          if (typeof theirs !== "string" || !theirs.trim()) problems.push(`missing ${key}`);
          else if (holes(theirs) !== holes(v)) problems.push(`placeholders ${key}`);
          else if (/!/.test(theirs)) problems.push(`exclamation ${key}`);
        } else walk(v as Record<string, unknown>, theirs as Record<string, unknown> | undefined, key);
      }
    };
    walk(en as unknown as Record<string, unknown>, hi as unknown as Record<string, unknown>, "");
    expect(problems).toEqual([]);
  });
});
