/**
 * Every user-facing string in the app. Plain English, Indian spelling (colour, not
 * color), sentence case, no exclamation marks — see docs/02-design-system.md "Voice".
 *
 * Hindi will be a second file with the same shape (Phase 8).
 */
export const en = {
  common: {
    appName: "HueVistaa",
    back: "Back",
    cancel: "Cancel",
    close: "Close",
    continue: "Continue",
    done: "Done",
    getHelp: "Get help",
    goHome: "Go home",
    retry: "Try again",
    save: "Save",
    signOut: "Sign out",
  },
  tabs: {
    home: "Home",
    studio: "Studio",
    catalogue: "Catalogue",
    boards: "Boards",
    account: "Account",
    points: "Points",
    scan: "Scan",
    rewards: "Rewards",
    nearby: "Nearby",
  },
  boot: {
    stillConnecting: "Still connecting…",
    cantReach: "We can't reach HueVistaa right now. Check your connection and try again.",
  },
  offline: {
    banner: "You're offline. Showing what was saved.",
  },
  errors: {
    network: "No connection. Check your internet and try again.",
    timeout: "That took too long. Try again.",
    server: "Something went wrong on our side. Try again in a moment.",
    tooMany: "Too many tries. Wait a few minutes and try again.",
    sessionEnded: "Please sign in again.",
    generic: "That didn't go through. Try again.",
  },
  validation: {
    mobile: "Enter a 10-digit mobile number, e.g. 98765 43210.",
    email: "Enter a valid email address.",
    passwordLength: "Choose a password of at least eight characters.",
    passwordMix: "Put at least one letter and one number in the password.",
    passwordHint: "At least eight characters, with a letter and a number.",
    shopCode: "Shop codes are 8 letters and numbers.",
  },
  disclaimer: {
    shades:
      "Shade colours are taken from the paint companies' own shade cards and fan decks. Screens, printing and lighting all shift colour, so what you see here can differ from the paint on the wall. Always check the physical shade card at the counter before you buy.",
    ai: "Previews are generated by AI. They are a guide to how a colour might look, not an exact picture of the finished wall — edges, textures and lighting can come out differently, and results are not guaranteed.",
  },
  notFound: {
    title: "Nothing here",
    body: "That link doesn't open anything in the app.",
  },
  planned: {
    eyebrow: "{id} · Phase {phase}",
    notBuilt: "Planned screen — not built yet.",
    spec: "Spec: {spec}",
    goesTo: "Goes to",
    params: "Opened with",
  },
  dev: {
    title: "Every screen",
    intro: "Development only. Preview a role to walk through the placeholders without a backend.",
    previewAs: "Preview as",
    signedOut: "Signed out",
    customer: "Customer",
    painter: "Painter",
    shop: "Shop",
    built: "built",
    planned: "planned",
  },
} as const;
